name: Linux CI

on: [push, pull_request]

env:
  gtksheet_version: 4.3.5
  # Allows for rebuilding the cache without bumping the version
  gtksheet_cache_version: 1

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ghc: ['8.4', '8.6', '8.8', '8.10']

    steps:
    - uses: actions/checkout@v1
    # At this point cabal.project refers to cabal files that do not exist,
    # hide it so that 'cabal update' does not fail.
    - name: Hide cabal project
      run: mv cabal.project _cabal.project
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: 'latest'
    - name: Restore cabal project
      run: mv _cabal.project cabal.project
    - name: Cache cabal store
      uses: actions/cache@v1
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal
    - name: Update cabal.project
      run: |
        sed -i.bak -e '/examples\/Handy\//d' cabal.project
        ./update-cabal-project.sh ubuntu-ci

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-dev
        ./bindings/PKGS.sh deps ubuntu-ci | sudo xargs apt-get install -y

    - uses: actions/cache@v1
      id: gtksheet-cache
      with:
        path: gtksheet
        key: ${{ env.gtksheet_version }}-${{ env.gtksheet_cache_version }}

    - uses: actions/checkout@v2
      if: steps.gtksheet-cache.outputs.cache-hit != 'true'
      with:
        repository: fpaquet/gtksheet
        ref: V${{ env.gtksheet_version}}
        path: gtksheet

    - name: Build GtkSheet from source
      if: steps.gtksheet-cache.outputs.cache-hit != 'true'
      run: |
        pushd gtksheet
        # Configure and install
        autoreconf -i
        # `libdir` is necessary because the system-configured location for GIR
        # files is not respected by the Makefile, and it will instead try
        # to install to `/usr/local/lib/`, which is wrong.
        # See https://github.com/haskell-gi/haskell-gi/pull/365
        ./configure --enable-introspection --libdir=/usr/lib/x86_64-linux-gnu/
        make
        popd

    - name: Install GtkSheet
      run: |
        pushd gtksheet
        sudo make install
        # The make install does this, but with -n
        # That means the lib cache doesn't get rebuilt, only links, and the
        # lib cache rebuild appears to be necessary
        sudo ldconfig
        popd

    - name: Generate bindings
      run: |
        pushd bindings
        cabal new-update
        cabal new-run genBuildInfo $(./PKGS.sh list ubuntu-ci)
        popd

    - name: Build
      run: cabal build all

    - name: Run tests
      run: cabal test
