name: Linux CI

on: [push, pull_request]

env:
  gtksheet_version: 4.3.2

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ghc: ['8.4', '8.6', '8.8', '8.10']

    steps:
    - uses: actions/checkout@v1
    # At this point cabal.project refers to cabal files that do not exist,
    # hide it so that 'cabal update' does not fail.
    - name: Hide cabal project
      run: mv cabal.project _cabal.project
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: 'latest'
    - name: Restore cabal project
      run: mv _cabal.project cabal.project
    - name: Cache cabal store
      uses: actions/cache@v1
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal
    - name: Update cabal.project
      run: |
        sed -i.bak -e '/examples\/Handy\//d' cabal.project
        ./update-cabal-project.sh ubuntu-ci

    - name: Install dependencies
      run: |
        sudo add-apt-repository -y ppa:gnome3-team/gnome3-staging
        sudo add-apt-repository -y ppa:gnome3-team/gnome3
        sudo apt-get update
        ./bindings/PKGS.sh deps ubuntu-ci | sudo xargs apt-get install -y

    - uses: actions/cache@v1
      id: gtksheet-cache
      with:
        path: gtksheet
        key: ${{ env.gtksheet_version }}

    - uses: actions/checkout@v2
      if: steps.gtksheet-cache.outputs.cache-hit != 'true'
      with:
        repository: fpaquet/gtksheet
        ref: V${{ env.gtksheet_version}}
        path: gtksheet

    - name: Build GtkSheet from source
      if: steps.gtksheet-cache.outputs.cache-hit != 'true'
      run: |
        pushd gtksheet
        # Configure and install
        autoreconf -i
        ./configure --enable-introspection
        make
        popd

    - name: Install GtkSheet
      run: |
        pushd gtksheet
        sudo make install
        # The make install does this, but with -n
        # That means the lib cache doesn't get rebuilt, only links, and the
        # lib cache rebuild appears to be necessary
        sudo ldconfig
        # Fix https://github.com/fpaquet/gtksheet/issues/23 - rename the typelib file
        sudo mv "/usr/local/lib/girepository-1.0/GtkSheet-4.0.typelib" "$(pkg-config gobject-introspection-1.0 --variable=typelibdir)/GtkSheet-${{ env.gtksheet_version }}.typelib"
        popd

    - name: Generate bindings
      run: |
        pushd bindings
        cabal new-update
        cabal new-run genBuildInfo $(./PKGS.sh list ubuntu-ci)
        popd

    - name: Build
      run: cabal build all --allow-newer=cairo:Cabal

    - name: Run tests
      run: cabal test --allow-newer=cairo:Cabal
